### ISSUE TITLE
CreateList组件问题

### ISSUE THREAD

**Issue by vito24** [freshesx/mogul#4]
1. labelCol和contentCol参数设置无效
2. 表单行间距过大
![image](https://user-images.githubusercontent.com/13133596/40966683-b899abb2-68e3-11e8-8230-69164fae5b7b.png)

**Comment by roger1253** [comment]
![image](https://user-images.githubusercontent.com/17668669/40967001-91983cee-68e4-11e8-8926-136a2941a4ff.png)
如图，即 labelCol : contentCol = 12 : 12 的渲染结果
![image](https://user-images.githubusercontent.com/17668669/40967074-bddfa8e6-68e4-11e8-97af-9231591782a6.png)
如图，即 labelCol : contentCol = 8 : 16 的渲染结果

可以看出 labelCol 和 contentCol 是可以生效的

**Comment by vito24** [comment]
知道问题所在了，如果使用了CreateFormItem，参数会不生效
![image](https://user-images.githubusercontent.com/13133596/40967539-d5a40b4c-68e5-11e8-8618-bfecb3790f8f.png)

**Comment by vito24** [comment]
嗯，我就是在这边做个记录，没想到你会回复哈哈
